/**:
  ros__parameters:
    n_threads: 4

    r_min: 0.2
    r_max: 50
    n_bins: 120
    n_segments: 360

    max_dist_to_line: 0.14

    sensor_height: 0.44
    # Match primary lidar for wave-road tolerance.
    min_slope: -1.2
    max_slope: 1.2
    max_fit_error: 0.08
    long_threshold: 1.0
    max_long_height: 0.16
    max_start_height: 0.5
    line_search_angle: 0.8

    gravity_aligned_frame: "odom"

    latch: false
    visualize: false

    input_topic: "/livox_right/lidar/pointcloud"
    obstacle_output_topic: "/segmentation/obstacle_right"
    ground_output_topic: "/segmentation/ground_right"
