base_link2livox_frame:
  rpy: '"0.0  0.0  0.0"'
  xyz: '"0.12 0.0 0.175"'
base_link2livox_right_frame:
  rpy: '"0.0 0.0 -0.610865"'
  xyz: '"0.12 -0.14 0.175"'
dual_lidar:
  enable: false
  nav2_consume_right: true
  obstacle_fusion_mode: separate
controller: dwb
lio: fastlio
localization: slam_toolbox
mode: nav
use_lio_rviz: false
use_sim: true
use_stvl: true
lidar_noise_stddev: 0.002
world: RMUL_26
